"""Add left_at to GroupMember and multi-currency/settlement to Expense

Revision ID: 39ec88143be6
Revises: 436ce15b2ebf
Create Date: 2026-06-13 11:57:14.856486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ec88143be6'
down_revision: Union[str, Sequence[str], None] = '436ce15b2ebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('currency', sa.String(), server_default='INR', nullable=False))
    op.add_column('expenses', sa.Column('original_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('expenses', sa.Column('is_settlement', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('group_members', sa.Column('left_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_members', 'left_at')
    op.drop_column('expenses', 'is_settlement')
    op.drop_column('expenses', 'original_amount')
    op.drop_column('expenses', 'currency')
    # ### end Alembic commands ###
